# -*- coding: utf-8 -*-
"""HemoScan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nUajhl5ybTv2Ijt8ZswxCd5qJcjv6agP
"""

!pip install scikit-learn matplotlib pandas

import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import ast
import os

from sklearn.model_selection import GroupShuffleSplit
from sklearn.metrics import mean_absolute_error

from google.colab import drive
drive.mount('/content/drive')

IMAGE_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 30
LEARNING_RATE = 0.0001
ANEMIA_THRESHOLD = 120  # g/L

metadata_path = "/content/drive/MyDrive/hemoscan/metadata.csv"
image_folder = "/content/drive/MyDrive/hemoscan/images"

df = pd.read_csv(metadata_path)

print("Total Rows:", len(df))
print("Unique Patients:", df['PATIENT_ID'].nunique())

df.head()

df.isnull().sum()

def crop_roi_safe(image, bbox):
    h, w, _ = image.shape
    x1, y1, x2, y2 = bbox

    # Clamp safely
    x1 = max(0, min(w, x1))
    x2 = max(0, min(w, x2))
    y1 = max(0, min(h, y1))
    y2 = max(0, min(h, y2))

    if x2 <= x1 or y2 <= y1:
        return None

    return image[y1:y2, x1:x2]

def build_roi_dataset(df, image_folder):

    images = []
    labels = []
    groups = []

    for _, row in df.iterrows():

        patient_id = row['PATIENT_ID']
        hb = row['HB_LEVEL_GperL']

        img_path = os.path.join(image_folder, f"{str(patient_id)}.jpg")

        image = cv2.imread(img_path)

        if image is None:
            print(f"Warning: Missing image {img_path}")
            continue

        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        # Correct orientation to match annotation
        image = cv2.rotate(image, cv2.ROTATE_90_CLOCKWISE)
        image = cv2.flip(image, 1)


        nail_boxes = ast.literal_eval(row['NAIL_BOUNDING_BOXES'])

        for box in nail_boxes:

            crop = crop_roi_safe(image, box)

            if crop is None or crop.size == 0:
                continue

            crop = cv2.resize(crop, (IMAGE_SIZE, IMAGE_SIZE))
            crop = crop / 255.0

            images.append(crop)
            labels.append(hb)
            groups.append(patient_id)

    return np.array(images), np.array(labels), np.array(groups)

X, y, groups = build_roi_dataset(df, image_folder)
X = X.astype(np.float32)



print("ROI Dataset Shape:", X.shape)

print("y shape:", y.shape)

print("groups shape:", groups.shape)

print("Dataset size in MB:", X.nbytes / (1024**2))

print(X.dtype)

X = X.astype(np.float32)

print("New dtype:", X.dtype)
print("Dataset size in MB:", X.nbytes / (1024**2))

print("Min Hb:", np.min(y))
print("Max Hb:", np.max(y))
print("Any NaN:", np.isnan(y).any())

import random

for _ in range(3):
    idx = random.randint(0, len(X)-1)
    plt.imshow(X[idx])
    plt.title(f"Hb: {y[idx]}")
    plt.axis("off")
    plt.show()

print(df['NAIL_BOUNDING_BOXES'].iloc[0])

img = cv2.imread(os.path.join(image_folder, "1.jpg"))
print(img.shape)

import matplotlib.pyplot as plt

row = df.iloc[0]
patient_id = row['PATIENT_ID']

img = cv2.imread(os.path.join(image_folder, f"{str(patient_id)}.jpg"))
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

boxes = ast.literal_eval(row['NAIL_BOUNDING_BOXES'])

plt.imshow(img)

for box in boxes:
    x1, y1, x2, y2 = box
    plt.gca().add_patch(
        plt.Rectangle((x1, y1),
                      x2 - x1,
                      y2 - y1,
                      edgecolor='red',
                      fill=False,
                      linewidth=2)
    )

plt.show()

rot90 = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
rot90_mirror = cv2.flip(rot90, 1)  # horizontal mirror

plt.imshow(rot90_mirror)

for box in boxes:
    x1, y1, x2, y2 = box
    plt.gca().add_patch(
        plt.Rectangle((x1, y1),
                      x2 - x1,
                      y2 - y1,
                      edgecolor='red',
                      fill=False,
                      linewidth=2)
    )

plt.title("90° Clockwise + Horizontal Mirror")
plt.show()

print("Image shape:", img.shape)
print("Boxes:", boxes)

import random

idx = random.randint(0, len(X)-1)

plt.imshow(X[idx])
plt.title(f"Hb: {y[idx]}")
plt.axis("off")
plt.show()

plt.hist(y, bins=20)
plt.title("Hb Distribution")
plt.show()

unique_counts = pd.Series(groups).value_counts()
print(unique_counts.head())

plt.hist(y, bins=20)
plt.title("Hb Distribution")
plt.xlabel("Hb Level (g/L)")
plt.ylabel("Frequency")
plt.show()

##splitting data for training and val

splitter = GroupShuffleSplit(test_size=0.2, random_state=42)
train_idx, val_idx = next(splitter.split(X, y, groups=groups))

X_train, X_val = X[train_idx], X[val_idx]
y_train, y_val = y[train_idx], y[val_idx]

print("Train Samples:", X_train.shape)
print("Validation Samples:", X_val.shape)

###computing the mean and std for train data only as hb range is too high
####added after training attempt 1
y_mean = np.mean(y_train)
y_std = np.std(y_train)

print("Train Mean:", y_mean)
print("Train Std:", y_std)

###normalize labels
#added after training attempt 1
y_train_norm = (y_train - y_mean) / y_std
y_val_norm = (y_val - y_mean) / y_std

set(groups[train_idx]) & set(groups[val_idx])

#checking to see if labels align
print(X_train.shape[0] == y_train.shape[0])
print(X_val.shape[0] == y_val.shape[0])

#quick gpu check
import tensorflow as tf
tf.config.list_physical_devices('GPU')

#nuilding model( transfer learning)
####training attemp 3 ( data augmenation to improve mae = 18.41)
def build_model():

    data_augmentation = tf.keras.Sequential([
        tf.keras.layers.RandomRotation(0.03),      # ~±3% rotation (very mild)
        tf.keras.layers.RandomBrightness(0.08),    # slight brightness change
    ])

    base_model = tf.keras.applications.MobileNetV2(
        input_shape=(224, 224, 3),
        include_top=False,
        weights='imagenet'
    )

    base_model.trainable = False

    inputs = tf.keras.Input(shape=(224, 224, 3))
    x = data_augmentation(inputs)          # augmentation applied here
    x = base_model(x, training=False)
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dense(128, activation='relu')(x)
    x = tf.keras.layers.Dropout(0.5)(x)
    outputs = tf.keras.layers.Dense(1, activation='linear')(x)

    model = tf.keras.Model(inputs, outputs)
### training attempt2- improvement using huber( before huber mae = 19.135)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(1e-4),
        loss=tf.keras.losses.Huber(),
        metrics=['mae']
    )

    return model

model = build_model()
model.summary()

early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_mae', patience=10, restore_best_weights=True)

#train model

history = model.fit(
    X_train,
    y_train_norm,
    validation_data=(X_val, y_val_norm),
    epochs=30,
    batch_size=32,
    callbacks=[early_stop]
)

preds_norm = model.predict(X_val)
preds = preds_norm * y_std + y_mean

mae = np.mean(np.abs(preds.flatten() - y_val))
print("Final Validation MAE:", mae)

##drawing bd range masks
# Define ranges
low_mask = y_val < 100
mid_mask = (y_val >= 100) & (y_val < 120)
high_mask = y_val >= 120

mae_low = np.mean(np.abs(preds[low_mask] - y_val[low_mask]))
mae_mid = np.mean(np.abs(preds[mid_mask] - y_val[mid_mask]))
mae_high = np.mean(np.abs(preds[high_mask] - y_val[high_mask]))

print("MAE (Hb < 100):", mae_low)
print("MAE (100–120):", mae_mid)
print("MAE (>120):", mae_high)

print("Low count:", np.sum(low_mask))
print("Mid count:", np.sum(mid_mask))
print("High count:", np.sum(high_mask))

#training graphs
plt.plot(history.history['mae'])
plt.plot(history.history['val_mae'])
plt.title("MAE Over Epochs")
plt.legend(["Train", "Validation"])
plt.show()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title("Loss Over Epochs")
plt.legend(["Train", "Validation"])
plt.show()

#evaluate

loss, mae = model.evaluate(X_val, y_val)
print("Validation MAE:", mae)

model.save("hemoscan_roi_model.keras")
print("Model saved successfully.")